#theme = "everforest_dark"
theme = "everforest_light"

[editor]
#gutters = ["diagnostics", "line-numbers"]
gutters = ["diagnostics",]
line-number = "absolute"
mouse = false
true-color = true
idle-timeout = 200
auto-pairs = true

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false

[editor.cursor-shape]
#insert = "bar"
#normal = "block"
#select = "underline"
normal = "underline"
insert = "bar"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"

[keys.normal]
C-s = ":w"
C-p = "rotate_view" 
C-r = ":reload"
w = "repeat_last_motion"

[keys.insert]
#j = {k = "normal_mode"}
left = "move_char_left"
right = "move_char_right"
down = "move_line_down"
up = "move_line_up"
C-a = "goto_line_start"
C-e = "goto_line_end_newline"
