[[grammar]]
name = "rust"
source = { git = "https://github.com/tree-sitter/tree-sitter-rust", rev = "f7fb205c424b0962de59b26b931fe484e1262b35" }

[[language]]
name = "rust"
config.ProcMacro.enable = true
config.cargo.features = "all"

[[language]]
name = "zh"
scope = "source.zh"
file-types = ["zh"]
roots = []
injection-regex="zh"
language-server = {command = "ds-pinyin-lsp"}
config.enabled=true
config.trace.server=true
config.prompt=true
config.show_status_bar=true
config.check_on_startup=true
config.db_path="/Users/wangli/dict.db3"

