[language-server.rust-analyzer]
command = "rust-analyzer"

[[grammar]]
name = "rust"
source = { git = "https://github.com/tree-sitter/tree-sitter-rust", rev = "f7fb205c424b0962de59b26b931fe484e1262b35" }

[[language]]
name = "rust"
language-servers = [ "rust-analyzer" ]
auto-format = true

[[language]]
name = "zh"
scope = "source.zh"
file-types = ["zh"]
roots = []
injection-regex="zh"
language-servers = [ "ds-pinyin-lsp" ]

[[language]]
name = "dyna"
scope = "source.k"
file-types = ["key","k"]
roots = []
injection-regex="k"
language-servers = [ "dkb" ]

[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "^typst$"
file-types = ["typ"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
roots = []
language-servers = [ "typst-lsp" ]

