[[grammar]]
name = "rust"
source = { git = "https://github.com/tree-sitter/tree-sitter-rust", rev = "f7fb205c424b0962de59b26b931fe484e1262b35" }


[[language]]
name = "rust"
config.ProcMacro.enable = true
config.cargo.features = "all"

