[[grammar]]
name = "rust"
source = { git = "https://github.com/tree-sitter/tree-sitter-rust", rev = "f7fb205c424b0962de59b26b931fe484e1262b35" }


[[language]]
name = "rust"
config.checkOnSave.overrideCommand = [
        "python3",
        "x.py",
        "check",
        "--json-output"
    ]
config.rustfmt.overrideCommand = [
      "./build/host/rustfmt/bin/rustfmt",
        "--edition=2021"
    ]
config.ProcMacro.server = "./build/host/stage0/libexec/rust-analyzer-proc-macro-srv"
config.ProcMacro.enable = true
config.cargo.buildScripts.enable = true
config.cargo.buildScripts.invocationLocation = "root"
config.cargo.buildScripts.invocationStrategy = "once"
config.cargo.buildScripts.overrideCommand = [
        "python3",
        "x.py",
        "check",
        "--json-output"
    ]
config.cargo.sysroot = "./build/host/stage0-sysroot"
config.rustc.source = "./Cargo.toml"

